### PR TITLE
Added ridon logo on device info (about)

### PR DESCRIPTION
**Pull request by rendrakesuma**

### CODE REVIEW

**Comment by emhaye** [comment]
App crash on open About

**Comment by rendrakesuma** [comment]
bisa di capture logcat nya?

**Comment by princeofgiri** [comment]
`--------- beginning of crash
01-01 12:58:59.204  2765  2765 E AndroidRuntime: FATAL EXCEPTION: main
01-01 12:58:59.204  2765  2765 E AndroidRuntime: Process: com.android.settings, PID: 2765
01-01 12:58:59.204  2765  2765 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.Settings$DeviceInfoSettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6128)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.support.v14.preference.PreferenceFragment.bindPreferences(PreferenceFragment.java:543)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.support.v14.preference.PreferenceFragment.onViewCreated(PreferenceFragment.java:336)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1010)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.Activity.performCreateCommon(Activity.java:6676)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	... 9 more
01-01 12:58:59.206   831  2729 W ActivityManager:   Force finishing activity com.android.settings/.Settings$DeviceInfoSettingsActivity
01-01 12:58:59.209   831  2729 W ActivityManager:   Force finishing activity com.android.settings/.Settings
01-01 12:58:59.276   831  4190 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
01-01 12:58:59.276   831  4190 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
01-01 12:58:59.276   831  4190 I Adreno-EGL: Build Date: 12/04/15 Fri
01-01 12:58:59.276   831  4190 I Adreno-EGL: Local Branch: mybranch17080070
01-01 12:58:59.276   831  4190 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.5
01-01 12:58:59.276   831  4190 I Adreno-EGL: Local Patches: NONE
01-01 12:58:59.276   831  4190 I Adreno-EGL: Reconstruct Branch: NOTHING
01-01 12:58:59.277   831  4190 I OpenGLRenderer: Initialized EGL, version 1.4
01-01 12:58:59.277   831  4190 D OpenGLRenderer: Swap behavior 1
01-01 12:58:59.709   831  1566 W ActivityManager: Activity pause timeout for ActivityRecord{7a4b56c u0 com.android.settings/.Settings$DeviceInfoSettingsActivity t17 f}
01-01 12:59:00.108   831  1566 I ActivityManager: Killing 3255:com.android.keychain/1000 (adj 904): empty #17
01-01 12:59:00.109   831  1566 I ActivityManager: Killing 2555:org.cyanogenmod.weather.provider/u0a31 (adj 906): empty #18
01-01 12:59:00.121   831  2236 D ActivityManager: cleanUpApplicationRecord -- 2555
01-01 12:59:00.136   831  1542 D ActivityManager: cleanUpApplicationRecord -- 3255
01-01 12:59:00.309  3286  3378 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
01-01 12:59:01.107  3479  3503 D InitAlarmsService: Clearing and rescheduling alarms.
01-01 12:59:02.310   270   430 D audio_hw_primary: out_standby: enter: stream (0xb623dec0) usecase(4: audio-ull-playback)
01-01 12:59:02.381   270   430 D hardware_info: hw_info_append_hw_type : device_name = speaker
01-01 12:59:03.085   831  1566 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{39d9415 u-1 android.intent.action.BATTERY_CHANGED} to ReceiverList{212b10a 2765 com.android.settings/1000/u0 remote:295ad75}: process crashing
`

**Comment by princeofgiri** [comment]
`
--------- beginning of crash
01-01 12:58:59.204  2765  2765 E AndroidRuntime: FATAL EXCEPTION: main
01-01 12:58:59.204  2765  2765 E AndroidRuntime: Process: com.android.settings, PID: 2765
01-01 12:58:59.204  2765  2765 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.Settings$DeviceInfoSettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6128)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.support.v14.preference.PreferenceFragment.bindPreferences(PreferenceFragment.java:543)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.support.v14.preference.PreferenceFragment.onViewCreated(PreferenceFragment.java:336)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1010)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.Activity.performCreateCommon(Activity.java:6676)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
01-01 12:58:59.204  2765  2765 E AndroidRuntime: 	... 9 more
01-01 12:58:59.206   831  2729 W ActivityManager:   Force finishing activity com.android.settings/.Settings$DeviceInfoSettingsActivity
01-01 12:58:59.209   831  2729 W ActivityManager:   Force finishing activity com.android.settings/.Settings
01-01 12:58:59.276   831  4190 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
01-01 12:58:59.276   831  4190 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
01-01 12:58:59.276   831  4190 I Adreno-EGL: Build Date: 12/04/15 Fri
01-01 12:58:59.276   831  4190 I Adreno-EGL: Local Branch: mybranch17080070
01-01 12:58:59.276   831  4190 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.5
01-01 12:58:59.276   831  4190 I Adreno-EGL: Local Patches: NONE
01-01 12:58:59.276   831  4190 I Adreno-EGL: Reconstruct Branch: NOTHING
01-01 12:58:59.277   831  4190 I OpenGLRenderer: Initialized EGL, version 1.4
01-01 12:58:59.277   831  4190 D OpenGLRenderer: Swap behavior 1
01-01 12:58:59.709   831  1566 W ActivityManager: Activity pause timeout for ActivityRecord{7a4b56c u0 com.android.settings/.Settings$DeviceInfoSettingsActivity t17 f}
01-01 12:59:00.108   831  1566 I ActivityManager: Killing 3255:com.android.keychain/1000 (adj 904): empty #17
01-01 12:59:00.109   831  1566 I ActivityManager: Killing 2555:org.cyanogenmod.weather.provider/u0a31 (adj 906): empty #18
01-01 12:59:00.121   831  2236 D ActivityManager: cleanUpApplicationRecord -- 2555
01-01 12:59:00.136   831  1542 D ActivityManager: cleanUpApplicationRecord -- 3255
01-01 12:59:00.309  3286  3378 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
01-01 12:59:01.107  3479  3503 D InitAlarmsService: Clearing and rescheduling alarms.
01-01 12:59:02.310   270   430 D audio_hw_primary: out_standby: enter: stream (0xb623dec0) usecase(4: audio-ull-playback)
01-01 12:59:02.381   270   430 D hardware_info: hw_info_append_hw_type : device_name = speaker
01-01 12:59:03.085   831  1566 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{39d9415 u-1 android.intent.action.BATTERY_CHANGED} to ReceiverList{212b10a 2765 com.android.settings/1000/u0 remote:295ad75}: process crashing

`

**Comment by rendrakesuma** [comment]
tolong di-test kembali

**Comment by emhaye** [comment]
Siap Pak

**Comment by emhaye** [comment]
Masih galat pak

```
04-19 20:38:41.693  5560  5560 D AndroidRuntime: Shutting down VM
04-19 20:38:41.694  5560  5560 E AndroidRuntime: FATAL EXCEPTION: main
04-19 20:38:41.694  5560  5560 E AndroidRuntime: Process: com.android.settings, PID: 5560
04-19 20:38:41.694  5560  5560 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.Settings$DeviceInfoSettingsActivity}: java.lang.IllegalStateException: The specified child already has a parent. You m
ust call removeView() on the child's parent first.
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6128)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-19 20:38:41.694  5560  5560 E AndroidRuntime: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.view.ViewGroup.addViewInner(ViewGroup.java:4417)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:4258)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:4198)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:4171)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1007)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.Activity.performCreateCommon(Activity.java:6676)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6684)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
04-19 20:38:41.694  5560  5560 E AndroidRuntime:        ... 9 more
04-19 20:38:41.696  3086  4550 W ActivityManager:   Force finishing activity com.android.settings/.Settings$DeviceInfoSettingsActivity
04-19 20:38:41.699  3086  4550 W ActivityManager:   Force finishing activity com.android.settings/.Settings
04-19 20:38:41.704  5560  5560 I Process : Sending signal. PID: 5560 SIG: 9
04-19 20:38:41.790  3086  3620 W InputDispatcher: channel 'ed7b196 com.android.settings/com.android.settings.Settings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-19 20:38:41.790  3086  3620 E InputDispatcher: channel 'ed7b196 com.android.settings/com.android.settings.Settings (server)' ~ Channel is unrecoverably broken and will be disposed!
04-19 20:38:41.790  3086  4396 D GraphicsStats: Buffer count: 4
04-19 20:38:41.791  3086  4596 I WindowManager: WIN DEATH: Window{ed7b196 u0 com.android.settings/com.android.settings.Settings}
04-19 20:38:41.791  3086  4596 W InputDispatcher: Attempted to unregister already unregistered input channel 'ed7b196 com.android.settings/com.android.settings.Settings (server)'
04-19 20:38:41.791  3086  3199 I ActivityManager: Process com.android.settings (pid 5560) has died
04-19 20:38:41.791  3086  3199 D ActivityManager: cleanUpApplicationRecord -- 5560
04-19 20:38:41.832  4994  5118 D mali_winsys: new_window_surface returns 0x3000,  [1536x2048]-format:1
```

**Comment by emhaye** [comment]
Not work

Thank you

**Pull request closed without merging**
